server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APP_NAME:gami}

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    url: jdbc:${RDB_TYPE:mysql}://${RDB_HOST:localhost}:${RDB_PORT:3306}/${RDB_SCHEMA:gami}?serverTimezone=${DB_TIMEZONE:Asia/Seoul}&characterEncoding=${DB_ENCODING:UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:hamin090403@gmail.com}
    password: ${MAIL_PASSWORD:fpkmypdxzazseekp}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

    auth-code-expiration-millis: 300000

jwt:
  accessSecret: ${JWT_ACCESS_SECRET:qXWbwKO97FDyg8AdNGh5SakyMHgdEdyfUZi3WPxKZ/c=}
  refreshSecret: ${JWT_REFRESH_SECRET:bddf2bea2033a184add4770ca6fe8957de4e175f2a295658d3dca73a458573c6}

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:https://discord.com/api/webhooks/1447956961822900274/dLeZY71KmqlLDghY9pcLnuCH_u3OMoSmrRcnrw0k2J9NIg-9h1HQdIrxQW5hRS0Ga21y}

app:
  env: ${APP_ENV:local}

cors:
  allowed-origins:
    - ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
    - ${CORS_ALLOWED_ORIGINS:http://gsmsv-1.yujun.kr:27919}